version: '3.8'

services:
  flask_app:
    build: ./flask_app
    port:
      - "5010:5010"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Capstone
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    ports:
      -"27017:27017"